import { StyleSheet } from 'react-native';
import ColorPalette from '../../config/ColorPalette';
import { getScreenHeight, getScreenWidth } from '../../helpers/screenSize';
import { Spacing } from '../../config/globalStyles';

export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    flexDirection: 'column',
    paddingVertical: getScreenHeight(1.2),
    // paddingHorizontal: getScreenHeight(2),
    backgroundColor: ColorPalette.WelcomeBack,
  },
  scrollContent: {
    gap: getScreenHeight(1.2),
  },
  deliveryInfo: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: getScreenHeight(2),
    paddingHorizontal: getScreenWidth(4),
    backgroundColor: ColorPalette.BLUE_00,
    borderRadius: Spacing.Small,
  },
  imageAllContainer: {
    display: 'flex',
    flexDirection: 'column',
    paddingVertical: getScreenHeight(2),
    paddingHorizontal: getScreenWidth(4),
    // borderRadius: Spacing.Small,
    gap: Spacing.XSmall,
    backgroundColor: ColorPalette.WHITE,
  },
  flatListImage: {
    width: '100%',
  },
  flatListContentContainer: {
    paddingVertical: Spacing.XSmall,
    gap: Spacing.XSmall,
  },
  similarProductImage: {
    width: getScreenWidth(20),
    height: getScreenHeight(10),
    borderRadius: Spacing.XSmall,
    backgroundColor: ColorPalette.WelcomeBack,
    resizeMode: 'contain',
  },
  sizeContainer: {
    display: 'flex',
    flexDirection: 'column',
    paddingVertical: getScreenHeight(2),
    paddingHorizontal: getScreenWidth(4),
    backgroundColor: ColorPalette.WHITE,
    gap: getScreenHeight(1.5),
    borderRadius: Spacing.Small,
  },
  horizontalListContainer: {
    gap: getScreenWidth(3),
  },
  bestSellerContainer: {
    display: 'flex',
    flexDirection: 'column',
    paddingHorizontal: getScreenWidth(4),
    paddingVertical: getScreenHeight(2),
    backgroundColor: ColorPalette.WHITE,
    borderRadius: Spacing.Small,
    gap: getScreenWidth(4),
  },
  footerContainer: {
    paddingVertical: getScreenHeight(6),
    paddingHorizontal: getScreenWidth(4),
    alignItems: 'flex-start',
    justifyContent: 'center',
    gap: getScreenHeight(2),
    backgroundColor: ColorPalette.Cart_BG,
  },
  footerText: {
    color: ColorPalette.BACKGROUND_GREY_200,
    textAlign: 'left',
  },
  footerLine: {
    width: '100%',
    height: 1,
    backgroundColor: ColorPalette.BACKGROUND_GREY_100,
  },
  actionButtonsContainer: {
    flexDirection: 'row',
    paddingHorizontal: getScreenWidth(4),
    paddingVertical: getScreenHeight(1.5),
    backgroundColor: ColorPalette.WHITE,
    borderTopWidth: 1,
    borderTopColor: ColorPalette.BACKGROUND_GREY_100,
    gap: getScreenWidth(3),
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  actionButton: {
    flex: 1,
    borderRadius: Spacing.Small,
  },
  view3dButton: {
    position: 'absolute',
    bottom: getScreenHeight(3),
    left: getScreenWidth(4),
    backgroundColor: ColorPalette.WHITE,
    paddingHorizontal: getScreenWidth(3),
    paddingVertical: getScreenHeight(0.8),
    borderRadius: 20,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    zIndex: 20,
  },
  view3dContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: getScreenWidth(2),
  },
  view3dIconWrapper: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: ColorPalette.ROSE_PURPLE_400,
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchContainer: {
    display: 'flex',
    flexDirection: 'row',
    padding: getScreenWidth(4),
    alignItems: 'center',
    backgroundColor: ColorPalette.WHITE,
    gap: getScreenWidth(4),
  },
  searchBoxContainer: {
    flex: 1,
    flexDirection: 'row',
    position: 'relative',
    alignItems: 'center',
  },
  searchInput: {
    flex: 1,
    paddingRight: getScreenWidth(10),
  },
  micIconContainer: {
    position: 'absolute',
    right: getScreenWidth(2),
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
